# Shell variables
# Generated by 'wal'
wallpaper='/home/hexov/Downloads/1.jpg'

# Special
background='#050506'
foreground='#e7e7e6'
cursor='#e7e7e6'

# Colors
color0='#050506'
color1='#7F8082'
color2='#919193'
color3='#9E9FA1'
color4='#B1B1B2'
color5='#BEC0C0'
color6='#D0D0D0'
color7='#e7e7e6'
color8='#a1a1a1'
color9='#7F8082'
color10='#919193'
color11='#9E9FA1'
color12='#B1B1B2'
color13='#BEC0C0'
color14='#D0D0D0'
color15='#e7e7e6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
