foreground   #e7e7e6
background   #050506
cursor       #e7e7e6

color0       #050506
color8       #a1a1a1
color1       #7F8082
color9       #7F8082
color2       #919193
color10      #919193
color3       #9E9FA1
color11      #9E9FA1
color4       #B1B1B2
color12      #B1B1B2
color5       #BEC0C0
color13      #BEC0C0
color6       #D0D0D0
color14      #D0D0D0
color7       #e7e7e6
color15      #e7e7e6
