#!/bin/sh

status() {
	if nmcli -t -f device con show --active | grep -q 'en'; then
		return 1
	elif nmcli -t -f device con show --active | grep -q 'wl'; then
		return 2
	else
		return 3
	fi
}

name() {
	status
	stat="$?"
	case "$stat" in
		1 )
			name=$(nmcli -t -f NAME,TYPE con show --active | grep ethernet | cut -d: -f1);;
		2 )
			name=$(nmcli -t -f NAME,TYPE con show --active | grep wireless | cut -d: -f1);;
		3 )
			name="Disconnected";;
	esac
	if [ "${#name}" -gt "12" ]; then
		name="$(echo "$name" | cut -c1-9)..."
	fi
	echo "$name"
}

case "$1" in
	"-s" )
		status
		case "$?" in
			1)
				echo "<span>  </span>";;
			2)
				echo "<span>  </span>";;
			3)
				echo "<span>  </span>";;
		esac;;
	"-n" )
		name;;
esac
