# програмы/софт

$terminal = kitty
$fileManager = kitty zsh -c "wal -i /home/hexov/Downloads/Untitled.jpg; clear; ranger; zsh"
$menu = quickshell -c ~/.config/quickshell/nandoroid ipc call spotlight toggle
$browser = zen-browser
$telegram = Telegram-Desktop
$obs = obs
$geminicli = kitty --directory ~/geminicli zsh -c "gemini; zsh"
$note = obsidian
$ide = zed
$screenshot = flameshot gui
$vpn = Hiddify
$sysmenu = quickshell -c ~/.config/quickshell/nandoroid ipc call session toggle
$kd-helper = python3 ~/.local/bin/kb-layout-helper.py

# для exec-once (системные службы)

$bar = quickshell -p ~/.config/quickshell/nandoroid
$notification = swaync
