input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options = grp:lalt_lshift_toggle
    kb_rules =
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = false
    }
}

#utps://wiki.hypr.land/Configuring/Variables/#gestures

#gestures {
 #   workspace_swipe = true
#}

# Example per-device config

# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
