# спкойно можно менять, но нне советую там где есть комменты

general {
  gaps_in = 7   # под бар. не трогать если не меняли бар!
  gaps_out = 9   # под бар. не трогать если не меняли бар!
  border_size = 0
  resize_on_border = true
  allow_tearing = false

  layout = dwindle
}

decoration {
  rounding = 7   # под бар. не трогать если не меняли бар!

  active_opacity = 0.92   # прозрачность активного окна
  inactive_opacity =0.89   # прозрачность не активного окна

  shadow {   # тени от  окон и т.д, они незамтные но очень все меняют
    enabled = true
    range = 15
    render_power = 10
    color = rgba(1a1a1aee)
  }

  blur {   # блюр (размытие) всего прозрачного
    enabled = true
    size = 7
    passes = 3
    vibrancy = 0.3
    xray = true
    #popups = true
  }

  dim_special = 0.3
}
