
  ########################
 ### переменные среды ###
########################

source = /home/hexov/.config/hypr/hyprland/env.conf

  ##############
 ## мониторы ##
##############

monitor= HDMI-A-1, 1920x1080@165, 0x0, 1, transform, 2 # ВАЖНО уберите (закоминтируйте) , transform, 2 это ПЕРЕВАРАЧИВАЕТ экран

  ################
 ### програмы ###
################

source = /home/hexov/.config/hypr/hyprland/apps.conf

  #################
 ### автострат ###
#################

source = /home/hexov/.config/hypr/hyprland/auto-start.conf

  ###########
 ### вид ###
###########

source = /home/hexov/.config/hypr/hyprland/vidio.conf

  ##############
 ## анимации ##
##############

source = /home/hexov/.config/hypr/hyprland/aimations.conf

  ############
 ### ввод ###
#############

source = /home/hexov/.config/hypr/hyprland/input.conf

  ###########
 ## бинды ##
###########

source = /home/hexov/.config/hypr/hyprland/binds.conf

  ####################
 ### окна и столы ###
#####################

# удобное распределение воркспейсов по мониторам(можно менять)

#workspace= name:1, monitor:DP-1
#workspace= name:2, monitor:HDMI-A-1
#workspace= name:3, monitor:DP-1
#workspace= name:4, monitor:DP-1
#workspace= name:5, monitor:HDIM-A-1
#workspace= name:6, monitor:HDIM-A-1
