--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/hexov/Downloads/Untitled.jpg"

-- Special
background="#0d0f12"
foreground="#c4c5c8"
cursor="#c4c5c8"

-- Colors
color0="#0d0f12"
color1="#5A5D62"
color2="#5E6166"
color3="#6E7176"
color4="#7A7D82"
color5="#7E8186"
color6="#888B90"
color7="#c4c5c8"
color8="#89898c"
color9="#5A5D62"
color10="#5E6166"
color11="#6E7176"
color12="#7A7D82"
color13="#7E8186"
color14="#888B90"
color15="#c4c5c8"
