# Shell variables
# Generated by 'wal'
wallpaper='/home/hexov/Downloads/Untitled.jpg'

# Special
background='#0d0f12'
foreground='#c4c5c8'
cursor='#c4c5c8'

# Colors
color0='#0d0f12'
color1='#5A5D62'
color2='#5E6166'
color3='#6E7176'
color4='#7A7D82'
color5='#7E8186'
color6='#888B90'
color7='#c4c5c8'
color8='#89898c'
color9='#5A5D62'
color10='#5E6166'
color11='#6E7176'
color12='#7A7D82'
color13='#7E8186'
color14='#888B90'
color15='#c4c5c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
