foreground   #d9d0c0
background   #010000
cursor       #d9d0c0

color0       #010000
color8       #979186
color1       #AD8B7B
color9       #AD8B7B
color2       #B67682
color10      #B67682
color3       #D3768C
color11      #D3768C
color4       #B89486
color12      #B89486
color5       #BDAE8E
color13      #BDAE8E
color6       #CA9590
color14      #CA9590
color7       #d9d0c0
color15      #d9d0c0
