[DEFAULT]
main_device = sonix-kd-65a-300100-gzr
monitor_interval = 0.2

[window_rules]
dev.zed.Zed = us
org.telegram.desktop = ru

[auto_detect]
enabled = true
threshold = 4
notify = true
auto_switch = false
keyboard_device = auto
