# програмы/софт

$terminal = kitty
$fileManager = kitty zsh -c "wal -i /home/hexov/Downloads/Untitled.jpg; clear; ranger; zsh"
$menu = rofi -show drun &
$browser = zen-browser
$telegram = Telegram-Desktop
$obs = obs
$geminicli = kitty --directory ~/geminicli zsh -c "gemini; zsh"
$note = obsidian
$ide = zed
$screenshot = flameshot gui
$vpn = Hiddify

# для exec-once (системные службы)

$bar = quickshell
$notification = swaync
