# нужное

exec-once = swww-daemon --format argb & sleep 0.5 && swww img /home/hexov/Downloads/1.jpg # обои
exec-once = $bar # бар
exec-once = sleep 2 # чтобы не было багов
exec-once = sleep 2 && hyprctl reloadconfig   # чтобы не было багов
exec-once = swaync   # уведомления

# приложения (можно менять)

exec-once = [workspace 1 silent] $terminal    # терминал
exec-once = [workspace 2 silent] $browser     # браузер
exec-once = [workspace 3 silent] $ide         # иде (редактор кода)
exec-once = [workspace 4 silent] $note        # заметки (обсидиан)
exec-once = [workspace 10 silent] $vpn        # впн (hiddify)
