# Сгенерировано hypr-themer — не редактируйте вручную

foreground #babaaf
background #0c0d07
cursor #babaaf
selection_foreground #0c0d07
selection_background #babaaf
color0 #0c0d07
color1 #484C37
color2 #5B623D
color3 #555945
color4 #5D614C
color5 #676A54
color6 #747665
color7 #babaaf
color8 #82827a
color9 #484C37
color10 #5B623D
color11 #555945
color12 #5D614C
color13 #676A54
color14 #747665
color15 #babaaf
