"""
eww.py — интеграция с EWW.

Генерирует colors-dynamic.scss из словаря цветов pywal
и перезагружает EWW.
"""

import time
from pathlib import Path

from config import Paths, Settings, Tools
from utils import ok, run, warn


# ── SCSS: кастомные переменные ────────────────────────────────────────────────
#
# Формат: (имя_переменной, значение_или_ссылка_на_wal_переменную)
# Правая часть — валидный SCSS (может быть переменной $wal-* или rgba(...))
#
CUSTOM_VARS: list[tuple[str, str]] = [
    # Меню
    ("menu-eventbox-color", "$wal-color4"),
    ("menu-eventbox-hover", "$wal-foreground"),
    ("power-color",         "$wal-color4"),
    ("menu-header-color",   "$wal-color4"),

    # Рабочие пространства / бар
    ("ws-color",            "$wal-foreground"),
    ("bar-bg",              "$wal-background"),
    ("div-color",           "rgba(205,212,246,0.3)"),
    ("tray-color",          "$wal-foreground"),

    # Время / дата
    ("time-bg",             "rgba(0,0,0,0.38)"),
    ("time-fg",             "$wal-foreground"),
    ("time-inner-color",    "$wal-color4"),
    ("date-inner-color",    "$wal-foreground"),
    ("cal-color",           "$wal-foreground"),
    ("cal-header-color",    "$wal-color3"),
    ("cal-button-hover",    "$wal-color1"),
    ("cal-highlight-color", "$wal-color9"),

    # Клавиатура
    ("keyboard-bg",         "rgba(0,0,0,0.38)"),
    ("kb-type-color",       "$wal-foreground"),

    # Звук / яркость
    ("volume-short-color",  "$wal-foreground"),
    ("vol-highlight",       "$wal-color4"),
    ("volume-slider-color", "$wal-color4"),
    ("lig-highlight",       "$wal-color4"),
    ("light-slider-color",  "$wal-color3"),
    ("vol-mini-highlight",  "$wal-color5"),

    # RAM / CPU / Диск
    ("ram-short-color",     "$wal-foreground"),
    ("cpu-header-color",    "$wal-color4"),
    ("cpu-color",           "$wal-color4"),
    ("cpu02-color",         "$wal-foreground"),
    ("ram-color",           "$wal-foreground"),
    ("ram02-color",         "$wal-foreground"),
    ("disk-color",          "$wal-color4"),
    ("disk02-color",        "$wal-foreground"),

    # Wi-Fi / Сеть
    ("wifi-type-color",     "$wal-foreground"),
    ("wifi-header-color",   "$wal-color4"),
    ("wifi-stats-color",    "$wal-foreground"),
    ("network-bg",          "rgba(0,0,0,0.28)"),
    ("nocon-color",         "$wal-color1"),
    ("yescon-color",        "$wal-color2"),
    ("wifi-ssid-01",        "$wal-foreground"),
    ("wifi-ssid-02",        "$wal-color4"),
    ("wifi-ssid-03",        "$wal-color2"),
    ("swifi-header-color",  "$wal-foreground"),

    # Питание
    ("shutdown-color",      "$wal-color4"),
    ("logout-hover",        "$wal-color4"),
    ("lockscr-color",       "$wal-color4"),
    ("reboot-hover",        "$wal-color4"),
    ("suspend-color",       "$wal-color4"),
    ("hibernate-hover",     "$wal-color4"),

    # Уведомления
    ("nheader-color",       "$wal-foreground"),
    ("clear-color",         "$wal-color1"),
    ("clear-hover",         "$wal-color3"),

    # Музыка
    ("main-title-color",    "$wal-color4"),
    ("artist-color",        "$wal-foreground"),
    ("music-highlight",     "$wal-color4"),
    ("music-timer-color",   "$wal-foreground"),
    ("mico-hover",          "$wal-color4"),

    # Пользователь
    ("username-color",      "$wal-foreground"),
    ("uptime-color",        "$wal-foreground"),
]


# ── Генерация SCSS ────────────────────────────────────────────────────────────

def generate_scss(colors: dict) -> None:
    """
    Генерирует colors-dynamic.scss.
    colors — словарь от wal.apply(): background, foreground, cursor, color0..15.
    Пропускает генерацию если EWW не установлен.
    """
    if not Tools.has_eww():
        warn("EWW не найден — SCSS пропущен")
        return

    Paths.EWW_DIR.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "// AUTOGENERATED FROM PYWAL — DO NOT EDIT MANUALLY",
        "",
        "// ── Base colors ──────────────────────────────────────────",
        f"$wal-background: {colors['background']};",
        f"$wal-foreground: {colors['foreground']};",
        f"$wal-cursor:     {colors['cursor']};",
        "",
        "// ── Color palette ────────────────────────────────────────",
    ]

    for i in range(16):
        lines.append(f"$wal-color{i}: {colors[f'color{i}']};")

    lines += [
        "",
        "// ── Custom variables (used by EWW widgets) ───────────────",
    ]

    for name, value in CUSTOM_VARS:
        lines.append(f"${name}: {value};")

    Paths.EWW_COLORS.write_text("\n".join(lines) + "\n")


def reload() -> None:
    """Перезагружает EWW с небольшой задержкой."""
    if not Tools.has_eww():
        return
    time.sleep(Settings.EWW_RELOAD_DELAY)
    run("eww reload")
