"""
swaync.py — интеграция с SwayNC.

Генерирует style.css из палитры pywal.
Сохраняет оригинальную структуру: анимации, углы, layout.
Шрифты НЕ трогаются.

Файл: ~/.config/swaync/style.css
"""

from color_utils import (
    darken, hex_add_alpha, hex_to_rgb,
    lighten, luminance, pick_best_accent,
)
from config import Paths, Tools
from utils import ok, warn
from pathlib import Path


# ── Путь к конфигу SwayNC ─────────────────────────────────────────────────────

SWAYNC_DIR  = Path.home() / ".config/swaync"
STYLE_FILE  = SWAYNC_DIR / "style.css"


# ── rgba хелпер для CSS ───────────────────────────────────────────────────────

def _r(hex_color: str, alpha: float) -> str:
    r, g, b = hex_to_rgb(hex_color)
    return f"rgba({r},{g},{b},{alpha:.2f})"


# ── Генерация CSS ─────────────────────────────────────────────────────────────

def _build_css(colors: dict) -> str:
    bg      = colors["background"]        # тёмный фон
    fg      = colors["foreground"]        # основной текст
    accent  = pick_best_accent(colors)    # насыщенный акцент
    err     = colors.get("color1", "#f38ba8")   # критические / ошибки
    warn_c  = colors.get("color3", "#f9e2af")   # предупреждения / яркость

    # Производные цвета
    bg_card   = darken(bg, 0.10)          # фон карточки уведомления
    bg_cc     = darken(bg, 0.08)          # фон notification center
    bg_widget = _r(fg, 0.05)             # фон виджетов (полупрозрачный)
    bg_btn    = _r(bg, 0.55)             # фон кнопок
    shadow    = _r(darken(bg, 0.40), 0.95)  # тень

    # Акцент с прозрачностью
    a10  = _r(accent, 0.10)
    a18  = _r(accent, 0.18)
    a22  = _r(accent, 0.22)
    a25  = _r(accent, 0.25)
    a38  = _r(accent, 0.38)
    a45  = _r(accent, 0.45)
    a12  = _r(accent, 0.12)

    # glow для анимации breathe
    glow_off = _r(accent, 0.00)
    glow_on  = _r(accent, 0.45)

    # critical glow
    crit_off = _r(err, 0.00)
    crit_on  = _r(err, 0.55)
    crit_mid = _r(err, 0.15)

    return f"""\
/* ═══════════════════════════════════════════════════════════════════
   SwayNC — style.css
   AUTOGENERATED FROM PYWAL — DO NOT EDIT
   ═══════════════════════════════════════════════════════════════════ */

/* ── Шрифт (не трогаем) ──────────────────────────────────────────── */
* {{
  font-family: "JetBrainsMono Nerd Font", monospace;
  font-size: 12px;
}}

/* ── Прозрачные обёртки (ОБЯЗАТЕЛЬНО) ───────────────────────────── */
notificationwindow,
.floating-notifications,
.blank-window,
blankwindow {{
  background: transparent;
}}
.floating-notifications .notification-row {{
  background: none;
}}

/* ═══════════════════════════════════════════════════════════════════
   KEYFRAMES
   ═══════════════════════════════════════════════════════════════════ */

@keyframes notif-enter {{
  0%   {{ opacity: 0;   margin-right: -30px; margin-left: 30px; }}
  55%  {{ opacity: 1;   margin-right: 3px;   margin-left: -3px; }}
  75%  {{ margin-right: -1px; margin-left: 1px; }}
  100% {{ opacity: 1;   margin-right: 0;     margin-left: 0; }}
}}

@keyframes breathe-accent {{
  0%   {{ box-shadow: 0 2px 4px 1px {shadow}, 0 0  6px 0px {glow_off}; }}
  50%  {{ box-shadow: 0 2px 4px 1px {shadow}, 0 0 18px 3px {glow_on}; }}
  100% {{ box-shadow: 0 2px 4px 1px {shadow}, 0 0  6px 0px {glow_off}; }}
}}

@keyframes pulse-ring {{
  0%   {{ box-shadow: 0 2px 4px 1px {shadow},
                     0 0  0px 0px {crit_off},
                     0 0  0px 0px {crit_off}; }}
  40%  {{ box-shadow: 0 2px 4px 1px {shadow},
                     0 0 20px 4px {crit_on},
                     0 0  8px 1px {_r(err, 0.30)}; }}
  70%  {{ box-shadow: 0 2px 4px 1px {shadow},
                     0 0 28px 8px {crit_mid},
                     0 0  4px 0px {_r(err, 0.10)}; }}
  100% {{ box-shadow: 0 2px 4px 1px {shadow},
                     0 0  0px 0px {crit_off},
                     0 0  0px 0px {crit_off}; }}
}}

@keyframes border-flicker {{
  0%,100% {{ border-left-color: {err}; }}
  45%     {{ border-left-color: {_r(err, 0.30)}; }}
  55%     {{ border-left-color: {_r(err, 0.30)}; }}
}}

@keyframes cc-fade {{
  from {{ opacity: 0; }}
  to   {{ opacity: 1; }}
}}

/* ═══════════════════════════════════════════════════════════════════
   ВСПЛЫВАЮЩИЕ УВЕДОМЛЕНИЯ
   ═══════════════════════════════════════════════════════════════════ */

.notification-row {{
  outline: none;
  margin: 5px 9px;
  animation: notif-enter 350ms cubic-bezier(0.22, 1, 0.36, 1) both;
}}

.notification-row .notification-background {{
  background: transparent;
  padding: 2px 3px;
}}

.notification-row .notification-background .notification {{
  background-color: {bg_card};
  border-radius: 14px 4px 14px 4px;
  border-left: 3px solid {accent};
  padding: 0;
  animation: breathe-accent 4s ease-in-out infinite;
}}

.notification-row .notification-background .notification.normal {{
  border-left-color: {accent};
  animation: breathe-accent 4s ease-in-out infinite;
}}

.notification-row .notification-background .notification.low {{
  border-left-color: {_r(fg, 0.25)};
  animation: none;
  box-shadow: 0 2px 4px 1px {_r(darken(bg, 0.40), 0.90)};
  background-color: {darken(bg_card, 0.05)};
}}

.notification-row .notification-background .notification.critical {{
  background-color: {darken(bg_card, 0.05)};
  border-left-color: {err};
  animation: pulse-ring 1.6s ease-in-out infinite,
             border-flicker 1.6s ease-in-out infinite;
}}

/* ── Кликабельная область ───────────────────────────────────────── */
.notification-row .notification-background .notification .notification-default-action {{
  background: transparent;
  border: none;
  border-radius: 14px 4px 14px 4px;
  color: {fg};
  padding: 12px 14px;
}}
.notification-row .notification-background .notification .notification-default-action:hover {{
  background-color: {a10};
}}
.notification-row .notification-background .notification .notification-default-action:not(:only-child) {{
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}}

/* ── Контент ────────────────────────────────────────────────────── */
.notification-row .notification-background .notification .notification-default-action .notification-content {{
  background: transparent;
  padding: 0;
}}
.notification-row .notification-background .notification .notification-default-action .notification-content .image {{
  -gtk-icon-size: 40px;
  border-radius: 8px;
  margin: 2px 12px 2px 0;
}}
.notification-row .notification-background .notification .notification-default-action .notification-content .app-icon {{
  -gtk-icon-size: 14px;
  margin: 4px;
}}
.notification-row .notification-background .notification .notification-default-action .notification-content .text-box label {{
  filter: none;
}}
.notification-row .notification-background .notification .notification-default-action .notification-content .text-box .summary {{
  font-size: 13px;
  font-weight: bold;
  color: #ffffff;
  background: transparent;
  text-shadow: none;
}}
.notification-row .notification-background .notification .notification-default-action .notification-content .text-box .time {{
  font-size: 10px;
  color: {_r(fg, 0.35)};
  background: transparent;
  text-shadow: none;
}}
.notification-row .notification-background .notification .notification-default-action .notification-content .text-box .body {{
  font-size: 11px;
  color: {_r(fg, 0.70)};
  background: transparent;
  text-shadow: none;
  margin-top: 3px;
}}
.notification-row .notification-background .notification .notification-default-action .notification-content progressbar trough {{
  background-color: {_r(bg, 0.50)};
  border-radius: 99px;
  min-height: 4px;
  margin-top: 6px;
}}
.notification-row .notification-background .notification .notification-default-action .notification-content progressbar progress {{
  background-color: {accent};
  border-radius: 99px;
}}

/* ── Кнопка закрытия ────────────────────────────────────────────── */
.close-button {{
  background: {_r(fg, 0.05)};
  color: {_r(fg, 0.45)};
  border: none;
  border-radius: 50%;
  min-width: 22px;
  min-height: 22px;
  padding: 0;
  margin: 8px 8px 0 0;
}}
.close-button:hover {{
  background: {_r(err, 0.20)};
  color: {err};
}}

/* ── Кнопки действий ────────────────────────────────────────────── */
.notification-row .notification-background .notification .notification-alt-actions {{
  background: {_r(bg, 0.25)};
  border-bottom-left-radius: 14px;
  border-bottom-right-radius: 4px;
  padding: 5px;
}}
.notification-row .notification-background .notification .notification-action {{
  margin: 0 3px;
  padding: 0;
}}
.notification-row .notification-background .notification .notification-action > button {{
  background: {a10};
  color: {accent};
  border-radius: 6px;
  border: 1px solid {_r(accent, 0.20)};
  padding: 5px 14px;
  font-size: 11px;
}}
.notification-row .notification-background .notification .notification-action > button:hover {{
  background: {a25};
  color: #ffffff;
  border-color: {a45};
}}

/* ═══════════════════════════════════════════════════════════════════
   ГРУППЫ УВЕДОМЛЕНИЙ
   ═══════════════════════════════════════════════════════════════════ */

.notification-group {{
  transition: opacity 200ms ease-in-out;
}}
.notification-group .notification-group-close-button .close-button {{
  margin: 10px 16px;
}}
.notification-group .notification-group-buttons,
.notification-group .notification-group-headers {{
  margin: 0 14px;
  color: {fg};
}}
.notification-group .notification-group-headers .notification-group-icon {{
  color: {_r(fg, 0.60)};
  -gtk-icon-size: 26px;
}}
.notification-group .notification-group-headers .notification-group-header {{
  color: #ffffff;
  font-weight: bold;
}}
.notification-group.collapsed.not-expanded {{
  opacity: 0.38;
}}
.notification-group.collapsed .notification-row .notification {{
  background-color: {bg_card};
}}
.notification-group.collapsed .notification-row:not(:last-child) .notification-action,
.notification-group.collapsed .notification-row:not(:last-child) .notification-default-action {{
  opacity: 0;
}}

/* ═══════════════════════════════════════════════════════════════════
   NOTIFICATION CENTER
   ═══════════════════════════════════════════════════════════════════ */

.control-center {{
  background-color: {bg_cc};
  color: {fg};
  border-radius: 18px 6px 18px 6px;
  box-shadow: 0 2px 3px 2px {shadow},
              0 0 30px 2px {a12};
  border: 1px solid {_r(accent, 0.10)};
  margin: 6px;
  animation: cc-fade 180ms ease both;
}}
.control-center .control-center-list {{
  background: transparent;
}}
.control-center .control-center-list-placeholder {{
  opacity: 0.38;
  color: {_r(fg, 0.50)};
}}
.control-center .control-center-list .notification-group,
.control-center .control-center-list .notification-group .notification-row,
.control-center .control-center-list .notification-group .notification-background {{
  background-color: transparent;
  box-shadow: none;
  border: none;
}}
.control-center .control-center-list .notification {{
  box-shadow: 0 1px 3px 1px {_r(darken(bg, 0.40), 0.60)};
  animation: none;
}}
.control-center .control-center-list .notification .notification-default-action,
.control-center .control-center-list .notification .notification-action {{
  transition: background 120ms ease-in-out;
}}
.control-center .control-center-list .notification .notification-default-action:hover,
.control-center .control-center-list .notification .notification-action:hover {{
  background-color: {_r(accent, 0.09)};
}}

/* ═══════════════════════════════════════════════════════════════════
   ВИДЖЕТЫ
   ═══════════════════════════════════════════════════════════════════ */

/* ── Заголовок ──────────────────────────────────────────────────── */
.widget-title {{
  background: transparent;
  padding: 16px 18px 10px;
}}
.widget-title > label {{
  font-size: 17px;
  font-weight: bold;
  color: #ffffff;
}}
.widget-title > button {{
  background-color: {_r(bg, 0.42)};
  color: {_r(fg, 0.40)};
  border-radius: 99px;
  border: none;
  padding: 3px 14px;
  font-size: 10px;
}}
.widget-title > button:hover {{
  background-color: {_r(err, 0.15)};
  color: {err};
}}

/* ── DND ────────────────────────────────────────────────────────── */
.widget-dnd {{
  background-color: {bg_widget};
  border-radius: 10px 3px 10px 3px;
  margin: 3px 8px;
  padding: 9px 16px;
  box-shadow: 0 1px 3px 1px {_r(darken(bg, 0.40), 0.50)};
}}
.widget-dnd label {{
  color: {_r(fg, 0.65)};
  font-size: 11px;
}}
.widget-dnd switch {{
  background-color: {_r(bg, 0.45)};
  border-radius: 99px;
  min-width: 36px;
  min-height: 18px;
  border: none;
}}
.widget-dnd switch:checked {{
  background-color: {err};
}}
.widget-dnd switch slider {{
  background-color: #ffffff;
  border-radius: 50%;
  min-width: 12px;
  min-height: 12px;
  margin: 3px;
  box-shadow: 0 1px 3px {_r(bg, 0.60)};
}}

/* ── Громкость ──────────────────────────────────────────────────── */
.widget-volume {{
  background-color: {bg_widget};
  border-radius: 10px 3px 10px 3px;
  margin: 3px 8px;
  padding: 10px 14px;
  box-shadow: 0 1px 3px 1px {_r(darken(bg, 0.40), 0.50)};
}}
.widget-volume label:first-child {{
  font-size: 17px;
  color: {accent};
  margin-right: 10px;
  line-height: 1.2;
}}
.widget-volume scale trough {{
  background-color: {_r(bg, 0.40)};
  border-radius: 99px;
  min-height: 6px;
  min-width: 238px;
  margin: 0 8px;
  box-shadow: inset 0 1px 3px {_r(bg, 0.60)};
}}
.widget-volume scale trough highlight {{
  background-color: {accent};
  border-radius: 99px;
}}

/* ── Яркость ────────────────────────────────────────────────────── */
.widget-backlight {{
  background-color: {bg_widget};
  border-radius: 10px 3px 10px 3px;
  margin: 3px 8px;
  padding: 10px 14px;
  box-shadow: 0 1px 3px 1px {_r(darken(bg, 0.40), 0.50)};
}}
.widget-backlight label:first-child {{
  font-size: 17px;
  color: {warn_c};
  margin-right: 10px;
  line-height: 1.2;
}}
.widget-backlight scale trough {{
  background-color: {_r(bg, 0.40)};
  border-radius: 99px;
  min-height: 6px;
  min-width: 238px;
  margin: 0 8px;
  box-shadow: inset 0 1px 3px {_r(bg, 0.60)};
}}
.widget-backlight scale trough highlight {{
  background-color: {warn_c};
  border-radius: 99px;
}}

/* ── MPRIS ──────────────────────────────────────────────────────── */
.widget-mpris {{
  padding: 0;
  margin: 3px 8px;
}}
.widget-mpris .widget-mpris-player {{
  margin: 4px 0;
  border-radius: 10px 3px 10px 3px;
  box-shadow: 0 2px 4px 2px {_r(darken(bg, 0.40), 0.80)};
  overflow: hidden;
}}
.widget-mpris .widget-mpris-player .mpris-background {{
  filter: blur(14px);
}}
.widget-mpris .widget-mpris-player .mpris-overlay {{
  padding: 14px;
  background-color: {_r(bg, 0.65)};
}}
.widget-mpris .widget-mpris-player .mpris-overlay .widget-mpris-album-art {{
  border-radius: 8px;
  -gtk-icon-size: 76px;
  box-shadow: 0 2px 6px {_r(bg, 0.70)};
}}
.widget-mpris .widget-mpris-player .mpris-overlay .widget-mpris-title {{
  font-weight: bold;
  font-size: 14px;
  color: #ffffff;
}}
.widget-mpris .widget-mpris-player .mpris-overlay .widget-mpris-subtitle {{
  font-size: 11px;
  color: {_r(fg, 0.65)};
}}
.widget-mpris .widget-mpris-player .mpris-overlay > box > button {{
  background: transparent;
  color: {_r(fg, 0.60)};
  border: none;
  border-radius: 6px;
  padding: 4px 8px;
  font-size: 20px;
}}
.widget-mpris .widget-mpris-player .mpris-overlay > box > button:hover {{
  background: {a18};
  color: {accent};
}}

/* ── Кнопки-сетка ───────────────────────────────────────────────── */
.widget-buttons-grid {{
  background-color: {bg_widget};
  border-radius: 10px 3px 10px 3px;
  margin: 3px 8px 8px;
  padding: 10px 12px;
  box-shadow: 0 1px 3px 1px {_r(darken(bg, 0.40), 0.50)};
}}
.widget-buttons-grid flowboxchild > button {{
  background-color: {bg_btn};
  color: {_r(fg, 0.60)};
  border-radius: 8px 2px 8px 2px;
  border: none;
  min-width: 50px;
  min-height: 44px;
  font-size: 18px;
  margin: 3px;
}}
.widget-buttons-grid flowboxchild > button:hover {{
  background-color: {a18};
  color: {accent};
}}
.widget-buttons-grid flowboxchild > button.toggle:checked {{
  background-color: {a22};
  color: {accent};
  border: 1px solid {a38};
}}
.widget-buttons-grid flowboxchild > button label {{
  font-size: 18px;
}}

/* ── Инхибиторы ─────────────────────────────────────────────────── */
.widget-inhibitors {{
  background-color: {bg_widget};
  border-radius: 10px 3px 10px 3px;
  margin: 3px 8px;
  padding: 8px 16px;
  box-shadow: 0 1px 3px 1px {_r(darken(bg, 0.40), 0.50)};
}}
.widget-inhibitors > label {{
  font-size: 17px;
  color: {warn_c};
  margin-right: 8px;
}}
.widget-inhibitors > button {{
  background-color: {bg_btn};
  color: {_r(fg, 0.40)};
  border: none;
  border-radius: 99px;
  padding: 2px 12px;
  font-size: 10px;
  margin-left: 8px;
}}
.widget-inhibitors > button:hover {{
  color: #ffffff;
}}

/* ── Tooltip ────────────────────────────────────────────────────── */
tooltip {{
  background-color: {_r(bg_card, 0.95)};
  border-radius: 10px;
  padding: 8px 12px;
  box-shadow: 0 2px 4px 1px {_r(darken(bg, 0.40), 0.90)},
              0 0 10px 1px {_r(accent, 0.18)};
  border: 1px solid {_r(accent, 0.12)};
}}
tooltip label {{
  color: {fg};
  font-size: 11px;
}}
"""


# ── Reload SwayNC ─────────────────────────────────────────────────────────────

def _reload() -> None:
    from utils import run
    run("swaync-client --reload-config")


# ── Публичный API ─────────────────────────────────────────────────────────────

def generate_style(colors: dict) -> None:
    """
    Генерирует style.css для SwayNC и перезагружает его.
    Пропускает если SwayNC не установлен.
    """
    if not Tools.available("swaync"):
        warn("SwayNC не найден — style.css пропущен")
        return

    SWAYNC_DIR.mkdir(parents=True, exist_ok=True)
    STYLE_FILE.write_text(_build_css(colors))
    ok(f"SwayNC style.css → {STYLE_FILE}")

    _reload()
