#!/bin/bash

THEMES_DIR="$HOME/.config/eww/themes"
CURRENT_THEME_FILE="$HOME/.config/eww/current-theme.txt"
CURRENT_WALIMG_FILE="$HOME/.config/eww/current-walimg.txt"
COLORS_FILE="$HOME/.config/eww/colors-dynamic.scss"

mkdir -p "$THEMES_DIR"

# =========================
# APPLY WALLPAPER (обычный режим)
# =========================
apply_wallpaper() {
    local WALLPAPER="$1"

    [ ! -f "$WALLPAPER" ] && echo "Обои не найдены" && exit 1

    # по умолчанию wal берёт цвет с этих же обоев
    echo "$WALLPAPER" > "$CURRENT_THEME_FILE"
    echo "$WALLPAPER" > "$CURRENT_WALIMG_FILE"

    wal -i "$WALLPAPER" -n -q
    swww img "$WALLPAPER" --transition-type fade --transition-fps 60 &

    source ~/.cache/wal/colors.sh

    cat > "$COLORS_FILE" << 'EOF'
// autogenerated by pywal
EOF

    echo "\$wal-background: $background;" >> "$COLORS_FILE"
    echo "\$wal-foreground: $foreground;" >> "$COLORS_FILE"
    echo "\$wal-cursor: $cursor;" >> "$COLORS_FILE"

    for i in {0..15}; do
        v="color$i"
        echo "\$wal-color$i: ${!v};" >> "$COLORS_FILE"
    done

    killall -SIGUSR1 kitty 2>/dev/null
    sleep 0.2
    eww reload

    echo "✓ Тема применена"
}

# =========================
# SAVE THEME
# =========================
save_theme() {
    local NAME="$1"
    [ -z "$NAME" ] && echo "save <name>" && exit 1

    local WALL
    WALL=$(cat "$CURRENT_THEME_FILE")

    local WALIMG
    WALIMG=$(cat "$CURRENT_WALIMG_FILE")

    echo "$WALL"   > "$THEMES_DIR/$NAME.theme"
    echo "$WALIMG" > "$THEMES_DIR/$NAME.walimg"
    cp "$COLORS_FILE" "$THEMES_DIR/$NAME.scss"

    echo "✓ Тема '$NAME' сохранена"
}

# =========================
# LOAD THEME
# =========================
load_theme() {
    local NAME="$1"
    [ -z "$NAME" ] && echo "load <name>" && exit 1

    local WALL_FILE="$THEMES_DIR/$NAME.theme"
    local WALIMG_FILE="$THEMES_DIR/$NAME.walimg"
    local SCSS_FILE="$THEMES_DIR/$NAME.scss"

    [ ! -f "$WALL_FILE" ] && echo "Тема не найдена" && exit 1

    local WALL
    WALL=$(cat "$WALL_FILE")

    local WALIMG
    WALIMG=$(cat "$WALIMG_FILE")

    # обои
    [ -f "$WALL" ] && {
        swww img "$WALL" --transition-type fade --transition-fps 60 &
        echo "$WALL" > "$CURRENT_THEME_FILE"
    }

    # EWW — кастомный SCSS
    [ -f "$SCSS_FILE" ] && cp "$SCSS_FILE" "$COLORS_FILE"

    # 🎨 wal берёт цвет из сохранённой картинки
    if [ -f "$WALIMG" ]; then
        wal -i "$WALIMG" -n -q
        echo "$WALIMG" > "$CURRENT_WALIMG_FILE"
    else
        echo "⚠ wal-картинка не найдена"
    fi

    killall -SIGUSR1 kitty 2>/dev/null
    sleep 0.2
    eww reload

    echo "✓ Тема '$NAME' загружена"
}

# =========================
# DELETE
# =========================
delete_theme() {
    rm -f "$THEMES_DIR/$1.theme" \
          "$THEMES_DIR/$1.walimg" \
          "$THEMES_DIR/$1.scss"
    echo "✓ Тема удалена"
}

# =========================
# LIST
# =========================
list_themes() {
    ls "$THEMES_DIR"/*.theme 2>/dev/null | sed 's|.*/||;s|\.theme||'
}

# =========================
# MAIN
# =========================
case "$1" in
    save) save_theme "$2" ;;
    load) load_theme "$2" ;;
    delete|remove) delete_theme "$2" ;;
    list) list_themes ;;
    *)
        [ -f "$1" ] && apply_wallpaper "$1" || {
            echo "usage:"
            echo "  theme.sh <wallpaper>"
            echo "  theme.sh save <name>"
            echo "  theme.sh load <name>"
        }
    ;;
esac
