"""
firefox.py — интеграция с Firefox.

Генерирует userChrome.css с CSS-переменными из палитры pywal.
Шрифты НЕ трогаются.

Требования:
  about:config → toolkit.legacyUserProfileCustomizations.stylesheets = true
  Затем перезапустить Firefox.

Профиль определяется автоматически (*.default-release → *.default).
Задать явно: config.py → Paths.FIREFOX_PROFILE = Path("~/.mozilla/firefox/XXXXX")
"""

from pathlib import Path

from color_utils import darken, lighten, pick_best_accent
from config import Paths, Tools
from utils import ok, warn


# ── Поиск профиля ─────────────────────────────────────────────────────────────

def _find_profile() -> Path | None:
    # 1. Явно задан в config.py
    if Paths.FIREFOX_PROFILE is not None:
        p = Path(Paths.FIREFOX_PROFILE).expanduser()
        return p if p.exists() else None

    # Список мест где может лежать профиль
    candidates = [
        Paths.FIREFOX_PROFILES_DIR,
        Path.home() / ".var/app/org.mozilla.firefox/.mozilla/firefox",  # Flatpak
        Path.home() / "snap/firefox/common/.mozilla/firefox",            # Snap
    ]

    for profiles_dir in candidates:
        if not profiles_dir.exists():
            continue
        for pattern in ("*.default-release", "*.default"):
            matches = sorted(
                p for p in profiles_dir.glob(pattern) if p.is_dir()
            )
            if matches:
                return matches[0]

    return None


# ── CSS переменные для rgba ───────────────────────────────────────────────────

def _rgba(hex_color: str, alpha: float) -> str:
    """hex + alpha → rgba(r, g, b, alpha) для Firefox CSS."""
    from color_utils import hex_to_rgb
    r, g, b = hex_to_rgb(hex_color)
    return f"rgba({r}, {g}, {b}, {alpha:.2f})"


# ── Генерация userChrome.css ──────────────────────────────────────────────────

def _build_userchrome(colors: dict) -> str:
    bg     = colors["background"]
    fg     = colors["foreground"]
    accent = pick_best_accent(colors)
    panel  = darken(bg, 0.06)
    hover  = lighten(bg, 0.10)
    border = _rgba(accent, 0.50)

    lines = [
        "/* AUTOGENERATED FROM PYWAL — DO NOT EDIT */",
        "/* Firefox userChrome.css — цвета интерфейса, шрифты не трогаем */",
        "/* Требуется: about:config → toolkit.legacyUserProfileCustomizations.stylesheets = true */",
        "",
        ":root {",
        f"  /* Панель инструментов */",
        f"  --toolbar-bgcolor:                      {panel} !important;",
        f"  --toolbar-color:                        {fg} !important;",
        f"  --toolbarbutton-hover-background:       {hover} !important;",
        f"  --toolbarbutton-active-background:      {_rgba(accent, 0.25)} !important;",
        f"  --toolbarbutton-icon-fill:              {fg} !important;",
        f"",
        f"  /* Адресная строка */",
        f"  --urlbar-background-color:              {panel} !important;",
        f"  --urlbar-box-bgcolor:                   {bg} !important;",
        f"  --urlbar-box-hover-bgcolor:             {hover} !important;",
        f"  --urlbar-box-active-bgcolor:            {_rgba(accent, 0.20)} !important;",
        f"  --urlbar-box-focus-bgcolor:             {bg} !important;",
        f"  --urlbar-popup-url-color:               {accent} !important;",
        f"",
        f"  /* Табы */",
        f"  --tab-selected-bgcolor:                 {bg} !important;",
        f"  --tab-hover-background-color:           {hover} !important;",
        f"  --tab-border-color:                     {border} !important;",
        f"  --tab-selected-textcolor:               {fg} !important;",
        f"",
        f"  /* Боковая панель */",
        f"  --sidebar-background-color:             {panel} !important;",
        f"  --sidebar-text-color:                   {fg} !important;",
        f"  --sidebar-border-color:                 {border} !important;",
        f"",
        f"  /* Акцент / выделение */",
        f"  --focus-outline-color:                  {accent} !important;",
        f"  --selected-item-color:                  {accent} !important;",
        f"  --selected-item-text-color:             #ffffff !important;",
        f"",
        f"  /* Рамки и разделители */",
        f"  --chrome-content-separator-color:       {border} !important;",
        f"  --toolbarseparator-color:               {border} !important;",
        f"",
        f"  /* Заголовок окна */",
        f"  --lwt-accent-color:                     {panel} !important;",
        f"  --lwt-text-color:                       {fg} !important;",
        f"  --lwt-tab-text:                         {fg} !important;",
        f"",
        f"  /* Контекстное меню */",
        f"  --arrowpanel-background:                {panel} !important;",
        f"  --arrowpanel-color:                     {fg} !important;",
        f"  --arrowpanel-border-color:              {border} !important;",
        f"  --panel-item-hover-bgcolor:             {hover} !important;",
        "}",
        "",
        "/* Принудительный фон панелей (для некоторых тем Firefox) */",
        f"#TabsToolbar      {{ background-color: {panel} !important; }}",
        f"#nav-bar          {{ background-color: {panel} !important; }}",
        f"#PersonalToolbar  {{ background-color: {darken(panel, 0.03)} !important; }}",
        "",
    ]
    return "\n".join(lines)


# ── Проверка about:config ─────────────────────────────────────────────────────

def _check_legacy_css(profile: Path) -> None:
    """Проверяет включён ли legacyUserProfileCustomizations в prefs.js."""
    prefs = profile / "prefs.js"
    if not prefs.exists():
        warn("⚠ Включи в Firefox: about:config → "
             "toolkit.legacyUserProfileCustomizations.stylesheets = true")
        return

    if "legacyUserProfileCustomizations.stylesheets\", true" in prefs.read_text():
        ok("legacyUserProfileCustomizations.stylesheets уже включён")
    else:
        warn("⚠ Открой about:config и включи:")
        warn("  toolkit.legacyUserProfileCustomizations.stylesheets = true")
        warn("  Затем ПЕРЕЗАПУСТИ Firefox")


# ── Публичный API ─────────────────────────────────────────────────────────────

def generate_colors(colors: dict) -> None:
    """
    Генерирует userChrome.css для профиля Firefox.
    Пропускает если Firefox не найден или профиль недоступен.
    """
    if not Tools.has_firefox():
        warn("Firefox не найден — userChrome.css пропущен")
        return

    profile = _find_profile()
    if profile is None:
        warn("Профиль Firefox не найден автоматически")
        warn("Укажи явно: config.py → Paths.FIREFOX_PROFILE = Path('...')")
        return

    chrome_dir = profile / "chrome"
    chrome_dir.mkdir(parents=True, exist_ok=True)

    css_file = chrome_dir / "userChrome.css"
    css_file.write_text(_build_userchrome(colors))
    ok(f"Firefox userChrome.css → {css_file}")

    _check_legacy_css(profile)
