"""
obsidian.py — интеграция с Obsidian.

Генерирует CSS-сниппет с переменными из палитры pywal
и кладёт его в .obsidian/snippets/ каждого vault.
Шрифты НЕ трогаются.

Настройка vault-ов:
  config.py → Paths.OBSIDIAN_VAULTS = [Path("~/Documents/MyVault")]

Активация сниппета в Obsidian:
  Settings → Appearance → CSS snippets → включить "wal-dynamic"
"""

from pathlib import Path

from color_utils import darken, hex_add_alpha, lighten, pick_best_accent
from config import Paths
from utils import ok, warn

SNIPPET_NAME = "wal-dynamic.css"


def _build_snippet(colors: dict) -> str:
    bg     = colors["background"]
    fg     = colors["foreground"]
    accent = pick_best_accent(colors)
    panel  = darken(bg, 0.05)
    hover  = lighten(bg, 0.08)
    border = hex_add_alpha(accent, 0.35)
    muted  = hex_add_alpha(fg, 0.45)
    c      = [colors.get(f"color{i}", fg) for i in range(16)]

    vars_block = (
        f"  /* Основные цвета */\n"
        f"  --background-primary:               {bg};\n"
        f"  --background-primary-alt:           {panel};\n"
        f"  --background-secondary:             {panel};\n"
        f"  --background-secondary-alt:         {darken(bg, 0.10)};\n"
        f"  --background-modifier-hover:        {hover};\n"
        f"  --background-modifier-active-hover: {hex_add_alpha(accent, 0.15)};\n"
        f"  --background-modifier-border:       {border};\n"
        f"\n"
        f"  /* Текст */\n"
        f"  --text-normal:                      {fg};\n"
        f"  --text-muted:                       {muted};\n"
        f"  --text-faint:                       {hex_add_alpha(fg, 0.30)};\n"
        f"  --text-on-accent:                   #ffffff;\n"
        f"  --text-accent:                      {accent};\n"
        f"  --text-accent-hover:                {lighten(accent, 0.15)};\n"
        f"\n"
        f"  /* Интерактивные элементы */\n"
        f"  --interactive-normal:               {panel};\n"
        f"  --interactive-hover:                {hover};\n"
        f"  --interactive-accent:               {accent};\n"
        f"  --interactive-accent-hover:         {lighten(accent, 0.10)};\n"
        f"\n"
        f"  /* Рамки */\n"
        f"  --divider-color:                    {border};\n"
        f"\n"
        f"  /* Теги */\n"
        f"  --tag-color:                        {accent};\n"
        f"  --tag-background:                   {hex_add_alpha(accent, 0.15)};\n"
        f"  --tag-background-hover:             {hex_add_alpha(accent, 0.25)};\n"
        f"\n"
        f"  /* Цитаты / блок-коды */\n"
        f"  --blockquote-border-color:          {accent};\n"
        f"  --code-background:                  {panel};\n"
        f"  --code-normal:                      {c[2]};\n"
        f"  --code-comment:                     {muted};\n"
        f"  --code-important:                   {c[1]};\n"
        f"  --code-value:                       {c[3]};\n"
        f"  --code-string:                      {c[2]};\n"
        f"  --code-keyword:                     {c[5]};\n"
        f"  --code-function:                    {c[4]};\n"
        f"  --code-operator:                    {c[1]};\n"
        f"\n"
        f"  /* Чекбоксы */\n"
        f"  --checkbox-color:                   {accent};\n"
        f"  --checklist-done-color:             {muted};\n"
        f"\n"
        f"  /* Скролл */\n"
        f"  --scrollbar-bg:                     transparent;\n"
        f"  --scrollbar-thumb-bg:               {hex_add_alpha(fg, 0.20)};\n"
    )

    return (
        "/* AUTOGENERATED FROM PYWAL — DO NOT EDIT */\n"
        "/* Obsidian CSS snippet — только цвета, шрифты не трогаем */\n"
        "/* Активация: Settings → Appearance → CSS snippets → wal-dynamic */\n\n"
        ".theme-dark,\n"
        ".theme-light {\n"
        + vars_block
        + "}\n"
    )


def generate_snippet(colors: dict) -> None:
    """
    Генерирует CSS сниппет для каждого vault из Paths.OBSIDIAN_VAULTS.
    Пропускает если vault-ы не настроены.
    """
    if not Paths.OBSIDIAN_VAULTS:
        warn("Obsidian vaults не настроены — пропускаем")
        warn("Укажи vault в config.py → Paths.OBSIDIAN_VAULTS")
        return

    css     = _build_snippet(colors)
    applied = 0

    for vault in Paths.OBSIDIAN_VAULTS:
        vault = Path(vault).expanduser()
        if not vault.exists():
            warn(f"Vault не найден: {vault}")
            continue

        snippets_dir = vault / ".obsidian" / "snippets"
        snippets_dir.mkdir(parents=True, exist_ok=True)
        (snippets_dir / SNIPPET_NAME).write_text(css)
        ok(f"Obsidian сниппет → {snippets_dir / SNIPPET_NAME}")
        applied += 1

    if applied == 0:
        warn("Ни один vault не был обновлён")
