"""
rofi.py — интеграция с Rofi.

Генерирует colors.rasi и АВТОМАТИЧЕСКИ прописывает @import в config.rasi.
Шрифты НЕ трогаются.
"""

from pathlib import Path

from color_utils import (
    darken,
    hex_add_alpha,
    lighten,
    pick_best_accent,
    pick_darkest,
    saturation,
)
from config import Paths, Tools
from utils import ok, warn

RASI_WIDTH = 600
IMPORT_LINE = '@import "colors.rasi"'  # без точки с запятой — Rofi не принимает


# ── Вычисление цветов ─────────────────────────────────────────────────────────


def _resolve(colors: dict) -> dict[str, str]:
    bg_key = pick_darkest(colors, [f"color{i}" for i in range(8)])
    bg = darken(colors[bg_key], 0.08)
    bg_light = lighten(bg, 0.12)
    accent = pick_best_accent(colors, bg_key="background")
    selected = darken(accent, 0.10)
    border = hex_add_alpha(accent, 0.75)
    grey_key = min(["color7", "color8"], key=lambda k: saturation(colors[k]))

    return {
        "bg": bg,
        "bg_light": bg_light,
        "border": border,
        "selected": selected,
        "accent": accent,
        "fg": "#ffffff",  # текст не трогаем
        "fg2": accent,
        "grey": colors[grey_key],
    }


# ── Генерация colors.rasi ─────────────────────────────────────────────────────


def _build_rasi(r: dict) -> str:
    rows = [
        ("bg-col", r["bg"], "фон"),
        ("bg-col-light", r["bg_light"], "фон активной строки"),
        ("border-col", r["border"], "рамка окна"),
        ("selected-col", r["selected"], "выбранный элемент"),
        ("blue", r["accent"], "акцент"),
        ("fg-col", r["fg"], "текст (всегда белый)"),
        ("fg-col2", r["fg2"], "акцентный текст"),
        ("grey", r["grey"], "приглушённый текст"),
    ]
    # Rofi требует формат:  variable-name: value;
    lines = ["/* AUTOGENERATED FROM PYWAL — DO NOT EDIT */", "* {"]
    for var, val, comment in rows:
        lines.append(f"    {var}: {val};  /* {comment} */")
    lines.append(f"    width: {RASI_WIDTH};")
    lines.append("}")
    return "\n".join(lines) + "\n"


# ── Подключение @import в config.rasi ─────────────────────────────────────────


def _ensure_import(config_rasi: Path) -> None:
    """
    Добавляет строку @import "colors.rasi" в начало config.rasi
    если её там ещё нет. Шрифты и остальное не трогает.
    """
    if not config_rasi.exists():
        # config.rasi нет — создаём минимальный с одним импортом
        config_rasi.write_text(f"{IMPORT_LINE}\n")
        ok(f"Создан {config_rasi.name} с @import")
        return

    content = config_rasi.read_text()

    if IMPORT_LINE in content:
        return  # уже есть

    # Вставляем в самое начало файла
    config_rasi.write_text(f"{IMPORT_LINE}\n\n{content}")
    ok(f"Добавлен @import в {config_rasi.name}")


# ── Дефолтная тема ────────────────────────────────────────────────────────────


def _save_default_if_missing(r: dict) -> None:
    default = Paths.EWW_THEMES_DIR / "default.rasi"
    if not default.exists():
        Paths.EWW_THEMES_DIR.mkdir(parents=True, exist_ok=True)
        default.write_text(_build_rasi(r))
        ok(f"Стартовая тема Rofi → {default}")


# ── Публичный API ─────────────────────────────────────────────────────────────


def generate_colors(colors: dict) -> None:
    if not Tools.has_rofi():
        warn("Rofi не найден — colors.rasi пропущен")
        return

    Paths.ROFI_DIR.mkdir(parents=True, exist_ok=True)

    resolved = _resolve(colors)
    _save_default_if_missing(resolved)

    # Пишем цвета
    Paths.ROFI_COLORS.write_text(_build_rasi(resolved))
    ok(f"Rofi colors.rasi → {Paths.ROFI_COLORS}")

    # Гарантируем что config.rasi подключает наш файл
    _ensure_import(Paths.ROFI_DIR / "config.rasi")
