"""
zed.py — интеграция с Zed Editor.

Генерирует JSON-тему и обновляет только поле "theme" в settings.json.
Шрифты НЕ трогаются.

settings.json у Zed в формате JSONC (комментарии + trailing commas) —
обрабатывается корректно без потери комментариев пользователя.

Файлы:
  ~/.config/zed/themes/wal-dynamic.json  — файл темы
  ~/.config/zed/settings.json            — обновляется только блок "theme"
"""

import json
import re

from color_utils import darken, hex_add_alpha, lighten, luminance, pick_best_accent
from config import Paths, Settings, Tools
from utils import ok, warn


# ── JSONC → JSON ──────────────────────────────────────────────────────────────

def _strip_jsonc(text: str) -> str:
    """
    Убирает из JSONC:
      — однострочные комментарии  // ...
      — многострочные комментарии /* ... */
      — trailing commas перед } и ]
    Возвращает валидный JSON.
    """
    # Убираем многострочные комментарии
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
    # Убираем однострочные комментарии
    text = re.sub(r'//[^\n]*', '', text)
    # Убираем trailing commas (перед } или ])
    text = re.sub(r',\s*([}\]])', r'\1', text)
    return text


# ── Hex + alpha → #rrggbbaa ───────────────────────────────────────────────────

def _hex8(hex_color: str, alpha: float) -> str:
    """Конвертирует hex + alpha → #rrggbbaa (формат Zed)."""
    from color_utils import hex_to_rgb
    r, g, b = hex_to_rgb(hex_color)
    return f"#{r:02x}{g:02x}{b:02x}{int(alpha * 255):02x}"


# ── Определение темной / светлой темы ────────────────────────────────────────

def _appearance(bg: str) -> str:
    return "dark" if luminance(bg) < 0.3 else "light"


# ── Построение JSON темы ──────────────────────────────────────────────────────

def _build_theme(colors: dict) -> dict:
    bg     = colors["background"]
    fg     = colors["foreground"]
    accent = pick_best_accent(colors)
    panel  = darken(bg, 0.06)
    hover  = lighten(bg, 0.08)
    muted  = _hex8(fg, 0.40)
    c      = [colors.get(f"color{i}", fg) for i in range(16)]

    return {
        "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
        "name":    Settings.ZED_THEME_NAME,
        "author":  "wal-dynamic (autogenerated)",
        "themes": [{
            "name":       Settings.ZED_THEME_NAME,
            "appearance": _appearance(bg),
            "style": {
                # Фон
                "background":              bg,
                "editor.background":       bg,
                "editor.foreground":       fg,
                "panel.background":        panel,
                "status_bar.background":   panel,
                "tab_bar.background":      panel,
                "toolbar.background":      panel,
                "title_bar.background":    panel,
                "tab.active_background":   bg,
                "tab.inactive_background": panel,
                # Текст
                "text":             fg,
                "text.muted":       muted,
                "text.placeholder": _hex8(fg, 0.30),
                "text.accent":      accent,
                "text.disabled":    _hex8(fg, 0.25),
                # Рамки
                "border":           _hex8(accent, 0.25),
                "border.variant":   _hex8(accent, 0.15),
                "border.focused":   accent,
                "border.selected":  accent,
                "border.disabled":  _hex8(fg, 0.10),
                # Элементы
                "element.active":      _hex8(accent, 0.20),
                "element.hover":       _hex8(accent, 0.10),
                "element.selected":    _hex8(accent, 0.20),
                "element.background":  hover,
                "element.disabled":    _hex8(fg, 0.10),
                # Редактор
                "editor.line_number":              muted,
                "editor.active_line_number":       accent,
                "editor.selection.background":     _hex8(accent, 0.25),
                "editor.active_line.background":   _hex8(accent, 0.06),
                "editor.highlighted_line.background": _hex8(accent, 0.08),
                "search.match_background":         _hex8(accent, 0.30),
                # Скроллбар
                "scrollbar.thumb.background":       _hex8(fg, 0.15),
                "scrollbar.thumb.hover_background": _hex8(fg, 0.30),
                "scrollbar.track.background":       panel,
                # Git
                "version_control.added":    c[2],
                "version_control.modified": c[3],
                "version_control.deleted":  c[1],
                "version_control.conflict": c[5],
                # Диагностика
                "error":   c[1],
                "warning": c[3],
                "info":    c[4],
                "hint":    muted,
                # Синтаксис
                "syntax": {
                    "comment":     {"color": muted, "font_style": "italic"},
                    "keyword":     {"color": c[5]},
                    "string":      {"color": c[2]},
                    "number":      {"color": c[3]},
                    "function":    {"color": c[4]},
                    "type":        {"color": c[6]},
                    "variable":    {"color": fg},
                    "operator":    {"color": c[1]},
                    "attribute":   {"color": c[3]},
                    "tag":         {"color": c[4]},
                    "property":    {"color": c[6]},
                    "punctuation": {"color": _hex8(fg, 0.50)},
                    "constant":    {"color": c[3]},
                    "boolean":     {"color": c[5]},
                    "namespace":   {"color": c[6]},
                    "constructor": {"color": c[4]},
                    "embedded":    {"color": c[2]},
                },
            },
        }],
    }


# ── Обновление settings.json ──────────────────────────────────────────────────

def _update_settings(theme_name: str) -> None:
    """
    Обновляет только блок "theme" в settings.json.
    Корректно читает JSONC (комментарии + trailing commas).
    Шрифты и все остальные поля НЕ трогаются.
    """
    path = Paths.ZED_SETTINGS
    path.parent.mkdir(parents=True, exist_ok=True)

    settings: dict = {}

    if path.exists():
        raw = path.read_text().strip()
        if raw:
            try:
                settings = json.loads(_strip_jsonc(raw))
            except json.JSONDecodeError as e:
                warn(f"Не удалось разобрать settings.json: {e}")
                warn("Создаём минимальный settings.json с темой")
                settings = {}

    # Обновляем только поле theme
    settings["theme"] = {
        "mode":  "dark",
        "dark":  theme_name,
        "light": theme_name,
    }

    # Пишем обратно как стандартный JSON (без комментариев)
    path.write_text(json.dumps(settings, indent=2, ensure_ascii=False) + "\n")
    ok(f"Zed settings.json → theme: {theme_name}")


# ── Публичный API ─────────────────────────────────────────────────────────────

def generate_theme(colors: dict) -> None:
    """
    Генерирует тему Zed и обновляет settings.json.
    Шрифты НЕ изменяются.
    """
    if not Tools.has_zed():
        warn("Zed не найден — тема пропущена")
        return

    Paths.ZED_THEMES_DIR.mkdir(parents=True, exist_ok=True)

    # Пишем файл темы
    theme_data = _build_theme(colors)
    Paths.ZED_THEME_FILE.write_text(
        json.dumps(theme_data, indent=2, ensure_ascii=False) + "\n"
    )
    ok(f"Zed тема → {Paths.ZED_THEME_FILE}")

    # Прописываем тему в settings.json
    _update_settings(Settings.ZED_THEME_NAME)
